---
title: "writing_functions"
author: "Amy Yeung"
date: "2022-10-27"
output: github_document
---

```{r, include=FALSE}
library(tidyverse)
library(rvest)
```

## Z-scores!!

```{r}
x_vec = rnorm(25, mean = 7, sd = 4)

# manual z score
(x_vec - mean(x_vec)) / sd(x_vec)
```

Suppose you want to do this often.

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  z = mean(x) / sd(x)
  
  z
}
```

```{r}
z_scores(x = x_vec)

z_scores(x = 1:10)
z_scores(x = rbinom(1000, 1, 0.6))

```

## Let's have multiple outputs

Let's just get the mean and sd from the vector input.

```{r}
mean_and_sd = function(x) {
    if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd(x)
  )
}

mean_and_sd(x_vec)
```


## Let's start with simulations

```{r}
x_vec = rnorm(n = 25000, mean = 7, sd = 4)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
```

Can I do this using a function? Yes!

```{r}
sim_mean_sd = function(n_obs, true_mean = 7, true_sd = 4) {
  
  x = rnorm(n = n_obs, mean = true_mean, sd = true_sd)

  tibble(
  mean = mean(x),
  sd = sd(x)
  )
}
```

Does it work?

```{r}
sim_mean_sd(2500, 10, 7)
```



```{r}
read_page_reviews <- function(url) {
  
  html = read_html(url)
  
  review_titles = 
    html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim() %>% 
    str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}
```

```{r}
read_page_reviews(url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=")
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)

dynamite_reviews
```



















